### PR TITLE
update to 1.5.1

### PR DESCRIPTION
**Pull request by SomeoneWeird**

### CODE REVIEW

**Comment by whiskers75** [comment]
If you don't mind, I'll gladly take that diff, and apply it to whiskers75/jsmc. :)
+1

**Comment by SomeoneWeird** [comment]
Why would I mind, that's how git is supposed to be used :)

**Comment by whiskers75** [comment]
I applied it way before you even said that :)

**Comment by SomeoneWeird** [comment]
then why ask..?

**Pull request closed without merging**
